// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"

	"github.com/jmgilman/headjack/internal/auth"
)

// Ensure, that PrompterMock does implement auth.Prompter.
// If this is not the case, regenerate this file with moq.
var _ auth.Prompter = &PrompterMock{}

// PrompterMock is a mock implementation of auth.Prompter.
//
//	func TestSomethingThatUsesPrompter(t *testing.T) {
//
//		// make and configure a mocked auth.Prompter
//		mockedPrompter := &PrompterMock{
//			PrintFunc: func(message string)  {
//				panic("mock out the Print method")
//			},
//			PromptChoiceFunc: func(prompt string, options []string) (int, error) {
//				panic("mock out the PromptChoice method")
//			},
//			PromptSecretFunc: func(prompt string) (string, error) {
//				panic("mock out the PromptSecret method")
//			},
//		}
//
//		// use mockedPrompter in code that requires auth.Prompter
//		// and then make assertions.
//
//	}
type PrompterMock struct {
	// PrintFunc mocks the Print method.
	PrintFunc func(message string)

	// PromptChoiceFunc mocks the PromptChoice method.
	PromptChoiceFunc func(prompt string, options []string) (int, error)

	// PromptSecretFunc mocks the PromptSecret method.
	PromptSecretFunc func(prompt string) (string, error)

	// calls tracks calls to the methods.
	calls struct {
		// Print holds details about calls to the Print method.
		Print []struct {
			// Message is the message argument value.
			Message string
		}
		// PromptChoice holds details about calls to the PromptChoice method.
		PromptChoice []struct {
			// Prompt is the prompt argument value.
			Prompt string
			// Options is the options argument value.
			Options []string
		}
		// PromptSecret holds details about calls to the PromptSecret method.
		PromptSecret []struct {
			// Prompt is the prompt argument value.
			Prompt string
		}
	}
	lockPrint        sync.RWMutex
	lockPromptChoice sync.RWMutex
	lockPromptSecret sync.RWMutex
}

// Print calls PrintFunc.
func (mock *PrompterMock) Print(message string) {
	if mock.PrintFunc == nil {
		panic("PrompterMock.PrintFunc: method is nil but Prompter.Print was just called")
	}
	callInfo := struct {
		Message string
	}{
		Message: message,
	}
	mock.lockPrint.Lock()
	mock.calls.Print = append(mock.calls.Print, callInfo)
	mock.lockPrint.Unlock()
	mock.PrintFunc(message)
}

// PrintCalls gets all the calls that were made to Print.
// Check the length with:
//
//	len(mockedPrompter.PrintCalls())
func (mock *PrompterMock) PrintCalls() []struct {
	Message string
} {
	var calls []struct {
		Message string
	}
	mock.lockPrint.RLock()
	calls = mock.calls.Print
	mock.lockPrint.RUnlock()
	return calls
}

// PromptChoice calls PromptChoiceFunc.
func (mock *PrompterMock) PromptChoice(prompt string, options []string) (int, error) {
	if mock.PromptChoiceFunc == nil {
		panic("PrompterMock.PromptChoiceFunc: method is nil but Prompter.PromptChoice was just called")
	}
	callInfo := struct {
		Prompt  string
		Options []string
	}{
		Prompt:  prompt,
		Options: options,
	}
	mock.lockPromptChoice.Lock()
	mock.calls.PromptChoice = append(mock.calls.PromptChoice, callInfo)
	mock.lockPromptChoice.Unlock()
	return mock.PromptChoiceFunc(prompt, options)
}

// PromptChoiceCalls gets all the calls that were made to PromptChoice.
// Check the length with:
//
//	len(mockedPrompter.PromptChoiceCalls())
func (mock *PrompterMock) PromptChoiceCalls() []struct {
	Prompt  string
	Options []string
} {
	var calls []struct {
		Prompt  string
		Options []string
	}
	mock.lockPromptChoice.RLock()
	calls = mock.calls.PromptChoice
	mock.lockPromptChoice.RUnlock()
	return calls
}

// PromptSecret calls PromptSecretFunc.
func (mock *PrompterMock) PromptSecret(prompt string) (string, error) {
	if mock.PromptSecretFunc == nil {
		panic("PrompterMock.PromptSecretFunc: method is nil but Prompter.PromptSecret was just called")
	}
	callInfo := struct {
		Prompt string
	}{
		Prompt: prompt,
	}
	mock.lockPromptSecret.Lock()
	mock.calls.PromptSecret = append(mock.calls.PromptSecret, callInfo)
	mock.lockPromptSecret.Unlock()
	return mock.PromptSecretFunc(prompt)
}

// PromptSecretCalls gets all the calls that were made to PromptSecret.
// Check the length with:
//
//	len(mockedPrompter.PromptSecretCalls())
func (mock *PrompterMock) PromptSecretCalls() []struct {
	Prompt string
} {
	var calls []struct {
		Prompt string
	}
	mock.lockPromptSecret.RLock()
	calls = mock.calls.PromptSecret
	mock.lockPromptSecret.RUnlock()
	return calls
}
